sudo: required

install: false

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -d book -D /documents/output manuscript.adoc

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - mkdir output/manuscript
  - cp -R $TRAVIS_BUILD_DIR/output/* output/manuscript-draft
  - mkdir output/manuscript-draft/imgs
  - cp -R $TRAVIS_BUILD_DIR/imgs/* output/manuscript-draft/imgs
  - git add output/*
  - git commit -m "Travis build sucessfull"
  - git push https://ypriverol:$GITHUB_TOKEN@$github.com/ypriverol/containers-rules-manuscript.git master > /dev/null 2>&1
