sudo: required

install: false

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR/:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -d book -D /documents/output manuscript.adoc

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - mkdir output/manuscript
  - cp -R $TRAVIS_BUILD_DIR/output/* output/manuscript-draft
  - mkdir output/manuscript-draft/img
  - cp -R $TRAVIS_BUILD_DIR/img/* output/manuscript-draft/img

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  keep-history: true
  on:
    branch: master
