sudo: required

install: false

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull alperyilmaz/asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR/:/documents/ --name asciidoc-to-html alperyilmaz/asciidoctor asciidoctor -r asciidoctor-bibliography -d book -D /documents/output manuscript.adoc
  - docker run -v $TRAVIS_BUILD_DIR/:/documents/ --name asciidoc-to-pdf alperyilmaz/asciidoctor asciidoctor-pdf -r asciidoctor-bibliography -d book -D /documents/output manuscript.adoc

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:
  - mkdir manuscript-draft
  - cp -R $TRAVIS_BUILD_DIR/output/* manuscript-draft/
  - mkdir manuscript-draft/imgs
  - cp -R $TRAVIS_BUILD_DIR/imgs/* manuscript-draft/imgs

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: manuscript-draft
  keep-history: true
  on:
    branch: master